데이터 불러옴

In [1]:
import urllib
from scipy import stats
from pandas import Series, DataFrame
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data'
raw_csv = urllib.request.urlopen(path)
col_names = range(23)
df = pd.read_csv(raw_csv, names = col_names)
print(len(df))

8124

In [2]:
df.head()

  0  1  2  3  4  5  6  7  8  9  ... 13 14 15 16 17 18 19 20 21 22
0  p  x  s  n  t  p  f  c  n  k ...  s  w  w  p  w  o  p  k  s  u
1  e  x  s  y  t  a  f  c  b  k ...  s  w  w  p  w  o  p  n  n  g
2  e  b  s  w  t  l  f  c  b  n ...  s  w  w  p  w  o  p  n  n  m
3  p  x  y  w  t  p  f  c  n  n ...  s  w  w  p  w  o  p  k  s  u
4  e  x  s  g  f  n  f  w  b  k ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 23 columns]

In [3]:
num_columns = df.shape[1]
map_dic = {}
for i in range(num_columns):
    unique_array = df[i].unique()
    N = len(unique_array)
    map_dic[i] = {}
    for j in range(N):
        map_dic[i][unique_array[j]] = j
    df[i] = df[i].map(map_dic[i])

In [4]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,1,0,1,0,0,1,0,...,0,0,0,0,0,0,0,1,1,1
2,1,1,0,2,0,2,0,0,1,1,...,0,0,0,0,0,0,0,1,1,2
3,0,0,1,2,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,3,1,3,0,1,1,0,...,0,0,0,0,0,0,1,1,2,1

In [5]:
for i in range(1, num_columns):
    unique_array = df[i].unique()
    N = len(unique_array)
    map_dic_sub = {}
    for j in range(N):
        if j == 0:
            map_dic_sub[j] = 0
        else:
            map_dic_sub[j] = j / float(N - 1)        
    df[i] = df[i].map(map_dic_sub)

In [6]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,0,0.0,0.000000,0.000000,0.0,0.000,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0,0.0,0.0,0.00,0.000,0.0,0.000000
1,1,0.0,0.000000,0.111111,0.0,0.125,0.0,0.0,1.0,0.000000,...,0.0,0.0,0.0,0,0.0,0.0,0.00,0.125,0.2,0.166667
2,1,0.2,0.000000,0.222222,0.0,0.250,0.0,0.0,1.0,0.090909,...,0.0,0.0,0.0,0,0.0,0.0,0.00,0.125,0.2,0.333333
3,0,0.0,0.333333,0.222222,0.0,0.000,0.0,0.0,0.0,0.090909,...,0.0,0.0,0.0,0,0.0,0.0,0.00,0.000,0.0,0.000000
4,1,0.0,0.000000,0.333333,1.0,0.375,0.0,1.0,1.0,0.000000,...,0.0,0.0,0.0,0,0.0,0.0,0.25,0.125,0.4,0.166667

In [7]:
data_df = df.iloc[:, 1:]

In [8]:
data_df.head()

,1,2,3,4,5,6,7,8,9,10,...,13,14,15,16,17,18,19,20,21,22
0,0.0,0.000000,0.000000,0.0,0.000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.00,0.000,0.0,0.000000
1,0.0,0.000000,0.111111,0.0,0.125,0.0,0.0,1.0,0.000000,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.00,0.125,0.2,0.166667
2,0.2,0.000000,0.222222,0.0,0.250,0.0,0.0,1.0,0.090909,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.00,0.125,0.2,0.333333
3,0.0,0.333333,0.222222,0.0,0.000,0.0,0.0,0.0,0.090909,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.00,0.000,0.0,0.000000
4,0.0,0.000000,0.333333,1.0,0.375,0.0,1.0,1.0,0.000000,1.0,...,0.0,0.0,0.0,0,0.0,0.0,0.25,0.125,0.4,0.166667

In [9]:
data_array = data_df.as_matrix()

In [10]:
print(type(data_array), data_array.shape)

<class 'numpy.ndarray'> (8124, 22)

In [11]:
label_df = df.iloc[:, 0:1]

In [12]:
label_df.head()

   0
0  0
1  1
2  1
3  0
4  1

In [13]:
label_array = label_df.as_matrix()

In [14]:
print(type(label_array), label_array.shape)

<class 'numpy.ndarray'> (8124, 1)

In [15]:
label_array_one_hot = []
for i in label_array:
    if i == 0:
        one_hot = [1, 0]
    else:
        one_hot = [0, 1]
    label_array_one_hot.append(one_hot)

In [16]:
label_array_one_hot =  np.array(label_array_one_hot)

In [17]:
print(type(label_array_one_hot), label_array_one_hot.shape)

<class 'numpy.ndarray'> (8124, 2)

In [18]:
train = {'data': None, 'labels': None}
validation = {'data': None, 'labels': None}
test = {'data': None, 'labels': None}

In [19]:
import random
pick = random.random()
train_data = []
train_labels = []
validation_data = []
validation_labels = []
test_data = []
test_labels = []
for i in range(len(data_array)):
    pick = random.random()
    if pick < 0.80:
        train_data.append(data_array[i])
        train_labels.append(label_array_one_hot[i])
    elif pick >= 0.80 and pick < 0.85:
        validation_data.append(data_array[i])
        validation_labels.append(label_array_one_hot[i])
    elif pick >= 0.85:
        test_data.append(data_array[i])
        test_labels.append(label_array_one_hot[i])
        
train['data'] = np.array(train_data)
train['labels'] = np.array(train_labels)
validation['data'] = np.array(validation_data)
validation['labels'] = np.array(validation_labels)
test['data'] = np.array(test_data)
test['labels'] = np.array(test_labels)

In [20]:
print(train['data'].shape, train['labels'].shape)

(6494, 22) (6494, 2)

In [21]:
print(validation['data'].shape, validation['labels'].shape)

(408, 22) (408, 2)

In [22]:
print(test['data'].shape, test['labels'].shape)

(1222, 22) (1222, 2)

multi layer 구성

In [42]:
import numpy as np
import matplotlib.pyplot as plt
#from tensorflow.examples.tutorials.mnist import input_data  mnist관련 필요없음
import math
import tensorflow as tf

#mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)  필요하지 않음

batch_size = 100
training_epochs = 100
learning_rate = 0.05

epoch_list = []
train_error_list = []
validation_error_list = []
test_accuracy_list = []
diff_index_list = []

# Network Parameters
n_input = 22 # Columns of data are 22
n_hidden_1 = 12 # 1st layer number of features  node 수가 128개까지 되지 않더라도 결과가 잘 나옴
n_hidden_2 = 12 # 2nd layer number of features
n_classes = 2 # Total class is 2 ( 독버섯, 식용버섯 )
    
# Data Preparation
x = tf.placeholder(tf.float32, [None, n_input])
y_target = tf.placeholder(tf.float32, [None, n_classes])

# Model Construction
# Store layers weight & bias
weights = {
    'W1': tf.Variable(tf.random_normal([n_input, n_hidden_1])),
    'W2': tf.Variable(tf.random_normal([n_hidden_1, n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_hidden_2, n_classes]))
}

biases = {
    'b1': tf.Variable(tf.random_normal([n_hidden_1])),
    'b2': tf.Variable(tf.random_normal([n_hidden_2])),
    'out': tf.Variable(tf.random_normal([n_classes]))
}

# 1st Hidden layer with RELU activation
u2 = tf.matmul(x, weights['W1']) + biases['b1']
z2 = tf.nn.relu(u2)

# 2ndHidden layer with RELU activation
u3 = tf.matmul(z2, weights['W2']) + biases['b2']
z3 = tf.nn.relu(u3)

# Output layer with linear activation
u_out = tf.matmul(z3, weights['out']) + biases['out']

# Target Setup
error = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=u_out, labels=y_target))
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(error)

# Accuracy   
prediction_and_ground_truth = tf.equal(tf.argmax(u_out, 1), tf.argmax(y_target, 1))
accuracy = tf.reduce_mean(tf.cast(prediction_and_ground_truth, tf.float32))

    
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    
    total_batch = int(math.ceil(len(train['data'])/float(batch_size)))  # total batch를 구하기 위함
    print("Total batch: %d" % total_batch)    

    for epoch in range(training_epochs):
        epoch_list.append(epoch)
        # Train Error Value
        train_error_value = sess.run(error, feed_dict={x: train['data'], y_target: train['labels']})  # 각각의 data를 맞게 넣어줌
        train_error_list.append(train_error_value)
        
        validation_error_value = sess.run(error, feed_dict={x: validation['data'], y_target: validation['labels']})
        validation_error_list.append(validation_error_value)
        
        test_accuracy_value = sess.run(accuracy, feed_dict={x: test['data'], y_target: test['labels']})
        test_accuracy_list.append(test_accuracy_value) 
        print("Epoch: {0:2d}, Train Error: {1:0.5f}, Validation Error: {2:0.5f}, Test Accuracy: {3:0.5f}".format(epoch, train_error_value, validation_error_value, test_accuracy_value))
        
        for i in range(total_batch):
            sess.run(optimizer, feed_dict={x: train['data'], y_target: train['labels']})
        
        
        #for i in range(total_batch):  mnist관련 optimizer를 위에 data로 대체
        #    batch_images, batch_labels = mnist.train.next_batch(batch_size)
        #    sess.run(optimizer, feed_dict={x: batch_images, y_target: batch_labels})
    

    # Draw Graph about Error Values & Accuracy Values
    #draw_error_values_and_accuracy()
    
    # False Prediction Profile
    prediction = sess.run(tf.argmax(u_out, 1), feed_dict={x:test['data']})
    ground_truth = sess.run(tf.argmax(y_target, 1), feed_dict={y_target:test['labels']})

    print(prediction)
    print(ground_truth)
    
    for i in range(len(test['data'])):
        if (prediction[i] != ground_truth[i]):
            diff_index_list.append(i)
            
    print("Number of False Prediction:", len(diff_index_list))

Total batch: 65
Epoch:  0, Train Error: 5.88340, Validation Error: 5.51539, Test Accuracy: 0.52455
Epoch:  1, Train Error: 0.29418, Validation Error: 0.30604, Test Accuracy: 0.88789
Epoch:  2, Train Error: 0.21013, Validation Error: 0.21620, Test Accuracy: 0.91735
Epoch:  3, Train Error: 0.16923, Validation Error: 0.17405, Test Accuracy: 0.93290
Epoch:  4, Train Error: 0.13965, Validation Error: 0.14285, Test Accuracy: 0.94517
Epoch:  5, Train Error: 0.11600, Validation Error: 0.11896, Test Accuracy: 0.95663
Epoch:  6, Train Error: 0.09688, Validation Error: 0.09876, Test Accuracy: 0.96563
Epoch:  7, Train Error: 0.08118, Validation Error: 0.08141, Test Accuracy: 0.96972
Epoch:  8, Train Error: 0.06864, Validation Error: 0.06785, Test Accuracy: 0.97463
Epoch:  9, Train Error: 0.05872, Validation Error: 0.05677, Test Accuracy: 0.97709
Epoch: 10, Train Error: 0.05083, Validation Error: 0.04838, Test Accuracy: 0.98036
Epoch: 11, Train Error: 0.04471, Validation Error: 0.04176, Test Accuracy: 0.98118
Epoch: 12, Train Error: 0.03985, Validation Error: 0.03647, Test Accuracy: 0.98363
Epoch: 13, Train Error: 0.03582, Validation Error: 0.03205, Test Accuracy: 0.98609
Epoch: 14, Train Error: 0.03242, Validation Error: 0.02842, Test Accuracy: 0.98854
Epoch: 15, Train Error: 0.02950, Validation Error: 0.02537, Test Accuracy: 0.98936
Epoch: 16, Train Error: 0.02695, Validation Error: 0.02276, Test Accuracy: 0.99100
Epoch: 17, Train Error: 0.02472, Validation Error: 0.02053, Test Accuracy: 0.99345
Epoch: 18, Train Error: 0.02278, Validation Error: 0.01861, Test Accuracy: 0.99427
Epoch: 19, Train Error: 0.02109, Validation Error: 0.01694, Test Accuracy: 0.99427
Epoch: 20, Train Error: 0.01960, Validation Error: 0.01553, Test Accuracy: 0.99509
Epoch: 21, Train Error: 0.01829, Validation Error: 0.01430, Test Accuracy: 0.99673
Epoch: 22, Train Error: 0.01711, Validation Error: 0.01320, Test Accuracy: 0.99673
Epoch: 23, Train Error: 0.01606, Validation Error: 0.01225, Test Accuracy: 0.99755
Epoch: 24, Train Error: 0.01511, Validation Error: 0.01140, Test Accuracy: 0.99755
Epoch: 25, Train Error: 0.01425, Validation Error: 0.01064, Test Accuracy: 0.99755
Epoch: 26, Train Error: 0.01347, Validation Error: 0.00996, Test Accuracy: 0.99755
Epoch: 27, Train Error: 0.01275, Validation Error: 0.00934, Test Accuracy: 0.99755
Epoch: 28, Train Error: 0.01210, Validation Error: 0.00878, Test Accuracy: 0.99755
Epoch: 29, Train Error: 0.01150, Validation Error: 0.00827, Test Accuracy: 0.99755
Epoch: 30, Train Error: 0.01095, Validation Error: 0.00781, Test Accuracy: 0.99836
Epoch: 31, Train Error: 0.01044, Validation Error: 0.00740, Test Accuracy: 0.99918
Epoch: 32, Train Error: 0.00997, Validation Error: 0.00702, Test Accuracy: 0.99918
Epoch: 33, Train Error: 0.00954, Validation Error: 0.00667, Test Accuracy: 0.99918
Epoch: 34, Train Error: 0.00914, Validation Error: 0.00635, Test Accuracy: 0.99918
Epoch: 35, Train Error: 0.00876, Validation Error: 0.00607, Test Accuracy: 0.99918
Epoch: 36, Train Error: 0.00841, Validation Error: 0.00580, Test Accuracy: 0.99918
Epoch: 37, Train Error: 0.00808, Validation Error: 0.00555, Test Accuracy: 0.99918
Epoch: 38, Train Error: 0.00777, Validation Error: 0.00532, Test Accuracy: 0.99918
Epoch: 39, Train Error: 0.00748, Validation Error: 0.00510, Test Accuracy: 0.99918
Epoch: 40, Train Error: 0.00721, Validation Error: 0.00489, Test Accuracy: 0.99918
Epoch: 41, Train Error: 0.00696, Validation Error: 0.00470, Test Accuracy: 0.99918
Epoch: 42, Train Error: 0.00672, Validation Error: 0.00453, Test Accuracy: 0.99918
Epoch: 43, Train Error: 0.00650, Validation Error: 0.00436, Test Accuracy: 0.99918
Epoch: 44, Train Error: 0.00629, Validation Error: 0.00421, Test Accuracy: 0.99918
Epoch: 45, Train Error: 0.00608, Validation Error: 0.00406, Test Accuracy: 0.99918
Epoch: 46, Train Error: 0.00589, Validation Error: 0.00393, Test Accuracy: 0.99918
Epoch: 47, Train Error: 0.00571, Validation Error: 0.00380, Test Accuracy: 0.99918
Epoch: 48, Train Error: 0.00554, Validation Error: 0.00368, Test Accuracy: 0.99918
Epoch: 49, Train Error: 0.00538, Validation Error: 0.00356, Test Accuracy: 0.99918
Epoch: 50, Train Error: 0.00522, Validation Error: 0.00346, Test Accuracy: 0.99918
Epoch: 51, Train Error: 0.00507, Validation Error: 0.00336, Test Accuracy: 0.99918
Epoch: 52, Train Error: 0.00492, Validation Error: 0.00326, Test Accuracy: 0.99918
Epoch: 53, Train Error: 0.00478, Validation Error: 0.00317, Test Accuracy: 0.99918
Epoch: 54, Train Error: 0.00465, Validation Error: 0.00309, Test Accuracy: 0.99918
Epoch: 55, Train Error: 0.00453, Validation Error: 0.00300, Test Accuracy: 0.99918
Epoch: 56, Train Error: 0.00440, Validation Error: 0.00292, Test Accuracy: 0.99918
Epoch: 57, Train Error: 0.00429, Validation Error: 0.00285, Test Accuracy: 0.99918
Epoch: 58, Train Error: 0.00418, Validation Error: 0.00277, Test Accuracy: 0.99918
Epoch: 59, Train Error: 0.00407, Validation Error: 0.00271, Test Accuracy: 0.99918
Epoch: 60, Train Error: 0.00396, Validation Error: 0.00264, Test Accuracy: 0.99918
Epoch: 61, Train Error: 0.00386, Validation Error: 0.00258, Test Accuracy: 0.99918
Epoch: 62, Train Error: 0.00377, Validation Error: 0.00252, Test Accuracy: 0.99918
Epoch: 63, Train Error: 0.00367, Validation Error: 0.00246, Test Accuracy: 0.99918
Epoch: 64, Train Error: 0.00358, Validation Error: 0.00241, Test Accuracy: 0.99918
Epoch: 65, Train Error: 0.00349, Validation Error: 0.00236, Test Accuracy: 0.99918
Epoch: 66, Train Error: 0.00341, Validation Error: 0.00231, Test Accuracy: 0.99918
Epoch: 67, Train Error: 0.00332, Validation Error: 0.00226, Test Accuracy: 0.99918
Epoch: 68, Train Error: 0.00324, Validation Error: 0.00222, Test Accuracy: 0.99918
Epoch: 69, Train Error: 0.00316, Validation Error: 0.00217, Test Accuracy: 0.99918
Epoch: 70, Train Error: 0.00309, Validation Error: 0.00213, Test Accuracy: 0.99918
Epoch: 71, Train Error: 0.00302, Validation Error: 0.00209, Test Accuracy: 0.99918
Epoch: 72, Train Error: 0.00295, Validation Error: 0.00205, Test Accuracy: 0.99918
Epoch: 73, Train Error: 0.00289, Validation Error: 0.00201, Test Accuracy: 0.99918
Epoch: 74, Train Error: 0.00283, Validation Error: 0.00197, Test Accuracy: 0.99918
Epoch: 75, Train Error: 0.00276, Validation Error: 0.00193, Test Accuracy: 0.99918
Epoch: 76, Train Error: 0.00271, Validation Error: 0.00189, Test Accuracy: 0.99918
Epoch: 77, Train Error: 0.00265, Validation Error: 0.00185, Test Accuracy: 0.99918
Epoch: 78, Train Error: 0.00259, Validation Error: 0.00182, Test Accuracy: 0.99918
Epoch: 79, Train Error: 0.00254, Validation Error: 0.00178, Test Accuracy: 0.99918
Epoch: 80, Train Error: 0.00249, Validation Error: 0.00175, Test Accuracy: 0.99918
Epoch: 81, Train Error: 0.00244, Validation Error: 0.00172, Test Accuracy: 0.99918
Epoch: 82, Train Error: 0.00239, Validation Error: 0.00169, Test Accuracy: 0.99918
Epoch: 83, Train Error: 0.00235, Validation Error: 0.00165, Test Accuracy: 0.99918
Epoch: 84, Train Error: 0.00230, Validation Error: 0.00162, Test Accuracy: 1.00000
Epoch: 85, Train Error: 0.00226, Validation Error: 0.00159, Test Accuracy: 1.00000
Epoch: 86, Train Error: 0.00222, Validation Error: 0.00156, Test Accuracy: 1.00000
Epoch: 87, Train Error: 0.00218, Validation Error: 0.00153, Test Accuracy: 1.00000
Epoch: 88, Train Error: 0.00214, Validation Error: 0.00151, Test Accuracy: 1.00000
Epoch: 89, Train Error: 0.00210, Validation Error: 0.00148, Test Accuracy: 1.00000
Epoch: 90, Train Error: 0.00206, Validation Error: 0.00145, Test Accuracy: 1.00000
Epoch: 91, Train Error: 0.00203, Validation Error: 0.00143, Test Accuracy: 1.00000
Epoch: 92, Train Error: 0.00199, Validation Error: 0.00140, Test Accuracy: 1.00000
Epoch: 93, Train Error: 0.00196, Validation Error: 0.00138, Test Accuracy: 1.00000
Epoch: 94, Train Error: 0.00193, Validation Error: 0.00135, Test Accuracy: 1.00000
Epoch: 95, Train Error: 0.00189, Validation Error: 0.00133, Test Accuracy: 1.00000
Epoch: 96, Train Error: 0.00186, Validation Error: 0.00131, Test Accuracy: 1.00000
Epoch: 97, Train Error: 0.00183, Validation Error: 0.00129, Test Accuracy: 1.00000
Epoch: 98, Train Error: 0.00180, Validation Error: 0.00127, Test Accuracy: 1.00000
Epoch: 99, Train Error: 0.00178, Validation Error: 0.00125, Test Accuracy: 1.00000
[1 1 1 ..., 0 1 1]
[1 1 1 ..., 0 1 1]
Number of False Prediction: 0

mnist보다 쉽게 분류